# Generated by Django 4.2.1 on 2023-06-24 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_userfii'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraction',
            name='date',
            field=models.DateField(default='2023-06-24'),
        ),
        migrations.AddField(
            model_name='useraction',
            name='handler',
            field=models.CharField(default='buy', max_length=255),
        ),
        migrations.AddField(
            model_name='useraction',
            name='trading_note',
            field=models.FileField(blank=True, null=True, upload_to='trading-notes/actions/'),
        ),
        migrations.CreateModel(
            name='ActionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handler', models.CharField(choices=[('B', 'buy'), ('S', 'sell'), ('J', 'jscp'), ('P', 'proceeds')], max_length=255)),
                ('date', models.DateField(default='2023-06-24')),
                ('quantity', models.IntegerField()),
                ('unit_price', models.FloatField()),
                ('total_price', models.FloatField()),
                ('trading_note', models.FileField(blank=True, null=True, upload_to='trading-notes/actions/')),
                ('useraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.useraction')),
            ],
        ),
    ]
