# Generated by Django 4.2.1 on 2023-06-27 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_useraction_date_useraction_handler_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionhistory',
            name='date',
            field=models.DateField(default='2023-06-26'),
        ),
        migrations.AlterField(
            model_name='useraction',
            name='date',
            field=models.DateField(default='2023-06-26'),
        ),
    ]
