# Generated by Django 4.2.1 on 2023-06-28 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_actionhistory_date_alter_useraction_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraction',
            name='trading_note',
        ),
        migrations.AlterField(
            model_name='actionhistory',
            name='date',
            field=models.DateField(default='2023-06-27'),
        ),
        migrations.AlterField(
            model_name='useraction',
            name='date',
            field=models.DateField(default='2023-06-27'),
        ),
    ]
