# Generated by Django 4.2.1 on 2023-06-30 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_useraction_trading_note_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FIIS',
            new_name='FII',
        ),
        migrations.AlterField(
            model_name='actionhistory',
            name='date',
            field=models.DateField(default='2023-06-29'),
        ),
        migrations.AlterField(
            model_name='useraction',
            name='date',
            field=models.DateField(default='2023-06-29'),
        ),
    ]
