# Generated by Django 4.2.1 on 2023-07-01 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_userfii_date_userfii_handler_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fiihistory',
            old_name='useraction',
            new_name='userfii',
        ),
    ]
