# Generated by Django 4.2.1 on 2023-07-02 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_rename_useraction_fiihistory_userfii'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actionhistory',
            old_name='useraction',
            new_name='userproduct',
        ),
        migrations.RenameField(
            model_name='fiihistory',
            old_name='userfii',
            new_name='userproduct',
        ),
        migrations.RenameField(
            model_name='useraction',
            old_name='action',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='userfii',
            old_name='fii',
            new_name='product',
        ),
        migrations.AlterField(
            model_name='actionhistory',
            name='date',
            field=models.DateField(default='2023-07-02'),
        ),
        migrations.AlterField(
            model_name='fiihistory',
            name='date',
            field=models.DateField(default='2023-07-02'),
        ),
        migrations.AlterField(
            model_name='useraction',
            name='date',
            field=models.DateField(default='2023-07-02'),
        ),
        migrations.AlterField(
            model_name='userfii',
            name='date',
            field=models.DateField(default='2023-07-02'),
        ),
    ]
