# Generated by Django 4.2.1 on 2023-07-05 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_rename_useraction_actionhistory_userproduct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionhistory',
            name='date',
            field=models.DateField(default='2023-07-04'),
        ),
        migrations.AlterField(
            model_name='fiihistory',
            name='date',
            field=models.DateField(default='2023-07-04'),
        ),
        migrations.AlterField(
            model_name='useraction',
            name='date',
            field=models.DateField(default='2023-07-04'),
        ),
        migrations.AlterField(
            model_name='userfii',
            name='date',
            field=models.DateField(default='2023-07-04'),
        ),
    ]
