# Generated by Django 4.2.1 on 2023-07-05 02:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0010_alter_actionhistory_date_alter_fiihistory_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductFixedIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('cdb', 'cdb'), ('cra', 'cra'), ('cri', 'cri'), ('lc', 'lc'), ('lci', 'lci'), ('lca', 'lca'), ('lf', 'lf'), ('lfsn', 'lfsn'), ('db', 'debêntures')], max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('value', models.FloatField()),
                ('grace_period', models.DateField(default='2023-07-01')),
                ('maturity_date', models.DateField(default='2023-07-01')),
                ('liquidity', models.CharField(choices=[('nv', 'no vencimento'), ('di', 'diária'), ('30d', '30 dias'), ('30d+', '30 dias +'), ('30d-', '30 dias -')], max_length=255)),
                ('profitability', models.CharField(max_length=255)),
                ('interest_receipt', models.CharField(choices=[('nh', 'não há'), ('m', 'mensal'), ('tm', 'trimestral'), ('sm', 'semestral'), ('a', 'anual')], max_length=255)),
                ('description', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
