# Generated by Django 4.2.1 on 2023-07-08 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_productfixedincome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfixedincome',
            name='category',
            field=models.CharField(choices=[('cdb', 'cdb'), ('cra', 'cra'), ('cri', 'cri'), ('lc', 'lc'), ('lci', 'lci'), ('lca', 'lca'), ('lf', 'lf'), ('lfsn', 'lfsn'), ('debêntures', 'debêntures')], max_length=255),
        ),
        migrations.AlterField(
            model_name='productfixedincome',
            name='interest_receipt',
            field=models.CharField(choices=[('não há', 'não há'), ('mensal', 'mensal'), ('trimestral', 'trimestral'), ('semestral', 'semestral'), ('anual', 'anual')], max_length=255),
        ),
        migrations.AlterField(
            model_name='productfixedincome',
            name='liquidity',
            field=models.CharField(choices=[('no vencimento', 'no vencimento'), ('diária', 'diária'), ('30 dias', '30 dias'), ('30 dias +', '30 dias +'), ('30 dias -', '30 dias -')], max_length=255),
        ),
    ]
