# Generated by Django 4.2.1 on 2023-07-12 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_alter_productfixedincome_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixedInomeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('apply', 'apply'), ('redeem', 'redeem')], default='apply', max_length=255)),
                ('date', models.DateField(default='2023-07-02')),
                ('value', models.FloatField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productfixedincome')),
            ],
        ),
    ]
