# Generated by Django 4.2.1 on 2023-07-12 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_fixedinomehistory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FixedInomeHistory',
            new_name='FixedIncomeHistory',
        ),
    ]
