# Generated by Django 4.2.1 on 2023-07-16 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_directtreasure'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectTreasureHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default='2023-07-02')),
                ('state', models.CharField(choices=[('apply', 'apply'), ('redeem', 'redeem')], max_length=255)),
                ('value', models.FloatField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.directtreasure')),
            ],
        ),
    ]
