# Generated by Django 4.2.1 on 2023-07-28 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_alter_fii_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfii',
            name='earnings_accumulated',
        ),
    ]
