# Generated by Django 4.2.1 on 2023-08-03 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_actionhistory_tax_and_irpf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedincomehistory',
            name='tax_and_irpf',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='fixedincomehistory',
            name='state',
            field=models.CharField(choices=[('apply', 'apply'), ('redeem', 'redeem'), ('profits', 'profits')], default='apply', max_length=255),
        ),
    ]
