# Generated by Django 4.2.1 on 2023-08-03 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_fixedincomehistory_tax_and_irpf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='directtreasurehistory',
            name='tax_and_irpf',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
