# Generated by Django 4.2.1 on 2023-08-03 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_directtreasurehistory_tax_and_irpf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productfixedincome',
            name='value',
        ),
        migrations.AlterField(
            model_name='productfixedincome',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
