# Generated by Django 4.2.1 on 2023-08-04 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_alter_fixedincomehistory_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixedincomehistory',
            name='state',
            field=models.CharField(choices=[('apply', 'aplicação'), ('redeem', 'resgate'), ('profits', 'recebimento de juros')], default='apply', max_length=255),
        ),
    ]
