# Generated by Django 4.2.1 on 2023-08-04 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0026_alter_fixedincomehistory_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixedincomehistory',
            name='tax_and_irpf',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='fixedincomehistory',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
