# Generated by Django 4.2.1 on 2023-08-04 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0027_alter_fixedincomehistory_tax_and_irpf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixedincomehistory',
            name='state',
            field=models.CharField(default='apply', max_length=255),
        ),
    ]
