# Generated by Django 4.2.1 on 2023-08-07 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0031_remove_directtreasure_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directtreasurehistory',
            name='state',
            field=models.CharField(choices=[('apply', 'apply'), ('redeem', 'redeem'), ('profits', 'recebimento de juros')], max_length=255),
        ),
    ]
