# Generated by Django 4.2.1 on 2023-08-10 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0032_alter_directtreasurehistory_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actionhistory',
            name='total_price',
        ),
    ]
