# Generated by Django 4.2.1 on 2023-08-10 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0033_remove_actionhistory_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraction',
            name='date',
        ),
        migrations.RemoveField(
            model_name='useraction',
            name='handler',
        ),
        migrations.RemoveField(
            model_name='useraction',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='useraction',
            name='unit_price',
        ),
    ]
