# Generated by Django 4.2.1 on 2023-08-11 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0035_remove_userfii_date_remove_userfii_handler_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fiihistory',
            name='total_price',
        ),
    ]
