# Generated by Django 4.2.1 on 2023-08-14 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0037_alter_action_cnpj_alter_action_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='cnpj',
            field=models.CharField(max_length=18, unique=True),
        ),
        migrations.AlterField(
            model_name='action',
            name='code',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
