# Generated by Django 4.2.1 on 2023-08-18 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0039_alter_action_cnpj_alter_action_code_alter_fii_cnpj_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='code',
            field=models.CharField(error_messages={'unique': 'Este código já está em uso'}, max_length=6, unique=True),
        ),
    ]
