# Generated by Django 4.2.1 on 2023-08-24 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0041_fiislastclose_actionslastclose'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fiislastclose',
            name='fii',
        ),
        migrations.AddField(
            model_name='action',
            name='last_close',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=15, null=True),
        ),
        migrations.DeleteModel(
            name='ActionsLastClose',
        ),
        migrations.DeleteModel(
            name='FIIsLastClose',
        ),
    ]
