# Generated by Django 4.2.1 on 2023-08-24 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0042_remove_fiislastclose_fii_action_last_close_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fii',
            name='last_close',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=15, null=True),
        ),
    ]
