# Generated by Django 4.2.1 on 2023-09-05 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0046_alter_fii_cnpj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='code',
            field=models.CharField(error_messages={'unique': 'Este código já está em uso'}, max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='fii',
            name='code',
            field=models.CharField(error_messages={'unique': 'Este código já está em uso'}, max_length=8, unique=True),
        ),
    ]
