# Generated by Django 4.2.1 on 2023-06-11 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_profile_cpf'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
