from dotenv import load_dotenv
import os


load_dotenv()


# HOUR FOR UPDATE LAST CLOSE VALUE - STOCKS
HOUR_UPDATE_LC_STOCKS = int(os.environ.get('HOUR_UPDATE_LC_STOCKS'))

# MINUTES FOR UPDATE LAST CLOSE VALUE - STOCKS
MINUTES_UPDATE_LC_STOCKS = int(os.environ.get('MINUTES_UPDATE_LC_STOCKS'))

# HOUR FOR UPDATE LAST CLOSE VALUE - FIIS
HOUR_UPDATE_LC_FIIS = int(os.environ.get('HOUR_UPDATE_LC_FIIS'))

# MINUTES FOR UPDATE LAST CLOSE VALUE - FISS
MINUTES_UPDATE_LC_FIIS = int(os.environ.get('MINUTES_UPDATE_LC_FIIS'))
