from django.urls import path
from django.views.generic import TemplateView
from . import views


app_name: str = 'product'


urlpatterns = [
    path('acoes/',
         views.ActionsView.as_view(),
         name='actions',
         ),
    path('acoes/lista/',
         views.AllActionsView.as_view(),
         name='actions_list',
         ),
    path('acoes/comprar/',
         views.ActionsBuyView.as_view(),
         name='actions_buy',
         ),
    path('acoes/vender/',
         views.ActionsSellView.as_view(),
         name='actions_sell',
         ),
    path('acoes/<str:code>/',
         views.ActionHistoryDetails.as_view(),
         name='action_history',
         ),
    path('fiis/',
         views.FIIsView.as_view(),
         name='fiis',
         ),
    path('fiis/lista/',
         views.AllFIIsView.as_view(),
         name='fiis_list'),
    path('fiis/comprar/',
         views.FIISBuyView.as_view(),
         name='fiis_buy',
         ),
    path('fiis/vender/',
         views.FIIsSellView.as_view(),
         name='fiis_sell',
         ),
    path('fiis/<str:code>/',
         views.FIIHistoryDetails.as_view(),
         name='fii_history',
         ),
    path('renda-fixa/',
         views.FixedIncomeView.as_view(),
         name='fixed_income',
         ),
    path('renda-fixa/registrar/',
         views.FixedIncomeRegisterView.as_view(),
         name='fixed_income_register',
         ),
    path('renda-fixa/<int:id>/editar/',
         views.FixedIncomeEditView.as_view(),
         name='fixed_income_edit',
         ),
    path('tesouro-direto/',
         TemplateView.as_view(
              template_name='product/pages/direct_treasure.html',
              ),
         name='direct_treasure',
         ),
]
